### ISSUE TITLE
Crash when AdvancedRocketry dimension begins 'doing weather'

### ISSUE THREAD

**Issue by MuteTiefling** [maruohon/justenoughdimensions#47]
Very simple. I see this after the world has been loaded for a while.

https://gist.github.com/MuteTiefling/a67dfe3a0807021cbea43bd393131f1c

I'm not sure what to make of it, or if there is something I need to change in my configurations. 

Right now, all I'm doing with JED is setting my spawn point to that dimension (dim 1008), enabling some vanilla game rules, and disabling the end/nether...

Dimensions config: https://gist.github.com/MuteTiefling/c40e52cb70835cc18b5ddad8fe8318f7

**Comment by MuteTiefling** [comment]
So I've just been informed that I wasn't using JED 1.6, so there's a good chance this is already fixed. I'm updating and will test. I'll close this up for now and re-open if anything.

**Comment by maruohon** [comment]
That crash will likely still happen, as your config causes JED to use its own WorldInfo object for that dimension. That should be fixed on Advanced Rocketry's side bu checking the type of the WorldInfo object before assuming that it's the vanilla `DerivedWorldInfo`.

**Comment by MuteTiefling** [comment]
Definitely still happening. I'll leave this closed for now and report to AR,
